language: php

notifications:
    email:
        on_success: never

php:
    - 7.3
    - 7.4

env:
  global:
    - XDEBUG_MODE=coverage

matrix:
    fast_finish: true
    include:
        -   php: 7.3
            env: dependencies=lowest

cache:
    directories:
        - $HOME/.composer/cache

before_script:
    - composer install -n
    - if [ "$dependencies" = "lowest" ]; then composer update --prefer-lowest --prefer-stable -n; fi;

after_script:
    # Submit coverage report to Coveralls servers, see .coveralls.yml
    - travis_retry php vendor/bin/coveralls -v
    # Submit coverage report to codecov.io
    - bash <(curl -s https://codecov.io/bash)

script:
    - composer test-coverage
